version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Building Docker image...
      - docker build -t 767397745665.dkr.ecr.us-east-1.amazonaws.com/solanki-api-repo:latest .
      - docker tag 767397745665.dkr.ecr.us-east-1.amazonaws.com/solanki-api-repo:latest 767397745665.dkr.ecr.us-east-1.amazonaws.com/solanki-api-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 767397745665.dkr.ecr.us-east-1.amazonaws.com/solanki-api-repo:latest
      - docker push 767397745665.dkr.ecr.us-east-1.amazonaws.com/solanki-api-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files: '**/*'
